import pytest
from ..data import DATA_DIR

from typing import NamedTuple, Optional
from antistasi_translation_sync.stringtable import StringtableParser, StringTable, ArmaLanguage
import dataclasses


@pytest.fixture(scope="function")
def parsed_simple_stringtable():
    file = DATA_DIR.joinpath("Stringtable_example_simple.xml")

    # text = file.read_text(encoding='utf-8', errors='ignore')

    parser = StringtableParser()

    stringtable = parser.parse(file)

    assert type(stringtable) == StringTable

    yield stringtable


@pytest.fixture(scope="function")
def parsed_intermediate_stringtable():
    file = DATA_DIR.joinpath("Stringtable_example_intermediate.xml")

    # text = file.read_text(encoding='utf-8', errors='ignore')

    parser = StringtableParser()

    stringtable = parser.parse(file)

    assert type(stringtable) == StringTable

    yield stringtable


@pytest.fixture(scope="function")
def parsed_complex_stringtable():
    file = DATA_DIR.joinpath("Stringtable_example_complex.xml")

    # text = file.read_text(encoding='utf-8', errors='ignore')

    parser = StringtableParser()

    stringtable = parser.parse(file)

    assert type(stringtable) == StringTable

    yield stringtable


class ExampleKeyData(NamedTuple):
    name: str
    language: ArmaLanguage
    text: str
    error: Optional[type[Exception]] = None


@dataclasses.dataclass(frozen=True)
class StringtableObjExpectedResult:
    header: str
    project_name: str
    package_name: str
    name: str

    amount_containers: int
    container_names: set[str]

    amount_keys: int
    key_names: set[str]
    example_keys: tuple[ExampleKeyData]

    amount_entries: int


@pytest.fixture
def simple_stringtable_expected_result():

    container_names = ["A3A_EXAMPLE_CONTAINER"]

    key_names = ["STR_A3A_EXAMPLE_KEY"]

    example_keys = [ExampleKeyData("STR_A3A_EXAMPLE_KEY", ArmaLanguage.ORIGINAL, "Hello World!")]

    yield StringtableObjExpectedResult(header='<?xml version="1.0" encoding="utf-8"?>',
                                       project_name="A3-Antistasi",
                                       package_name="A3-Antistasi Simple",
                                       name="Simple",
                                       amount_containers=1,
                                       container_names=set(container_names),
                                       amount_keys=1,
                                       key_names=set(key_names),
                                       example_keys=tuple(example_keys),
                                       amount_entries=11)


@pytest.fixture
def intermediate_stringtable_expected_result():

    container_names = ["A3A_EXAMPLE_CONTAINER",
                       "A3A_SECOND_EXAMPLE_CONTAINER",
                       "A3A_EMPTY_EXAMPLE_CONTAINER"]

    key_names = ["STR_A3A_EXAMPLE_KEY",
                 "STR_A3A_SECOND_EXAMPLE_KEY",
                 "STR_A3A_EMPTY_EXAMPLE_KEY"]

    example_keys = [ExampleKeyData("STR_A3A_EXAMPLE_KEY", ArmaLanguage.ORIGINAL, "Hello World!"),
                    ExampleKeyData("STR_A3A_SECOND_EXAMPLE_KEY", ArmaLanguage.ORIGINAL, "My foo is your bar"),
                    ExampleKeyData("STR_A3A_EMPTY_EXAMPLE_KEY", ArmaLanguage.ORIGINAL, None, error=KeyError)]

    yield StringtableObjExpectedResult(header='<?xml version="1.0" encoding="utf-8"?>',
                                       project_name="A3-Antistasi",
                                       package_name="A3-Antistasi Intermediate",
                                       name="Intermediate",
                                       amount_containers=3,
                                       container_names=set(container_names),
                                       amount_keys=3,
                                       key_names=set(key_names),
                                       example_keys=tuple(example_keys),
                                       amount_entries=12)


@pytest.fixture
def complex_stringtable_expected_result():

    container_names = ['A3A_GCTracker',
                       'A3A_actions',
                       'A3A_customHint',
                       'A3A_garrisons',
                       'AI_management',
                       'Base',
                       'Utility_Items',
                       'carpet_bombing',
                       'commander_comm',
                       'construction_menu',
                       'credits_generic',
                       'dialog_build_menu',
                       'dialog_build_minefield',
                       'dialog_garrison_recruit',
                       'dialog_generic',
                       'dialog_headquarters',
                       'dialog_load_previous_session',
                       'dialog_unit_recruit',
                       'dialog_vehicle_purchase',
                       'dialog_vehicle_purchase_civ',
                       'dialog_vehicle_purchase_military',
                       'diff_menu',
                       'dismiss_menu',
                       'gameMode_menu',
                       'game_options',
                       'garage_sell',
                       'journal_entries',
                       'mission_check',
                       'mission_menu',
                       'mortar_type',
                       'player_money',
                       'radio_comm',
                       'server_info',
                       'squad_manager',
                       'squad_options',
                       'squad_recruit',
                       'time_units',
                       'vehicle_manager']

    key_names = ['STR_A3A_GCTracker_tracker_notification',
                 'STR_A3A_GCTracker_tracker_ran_gc',
                 'STR_A3A_GCTracker_tracker_title',
                 'STR_A3A_Packable_Objects_Title',
                 'STR_A3A_Packable_Objects_refunding_error',
                 'STR_A3A_Utility_Items_Feedback_Attached_Objects',
                 'STR_A3A_Utility_Items_Feedback_Far',
                 'STR_A3A_Utility_Items_Feedback_Normal',
                 'STR_A3A_Utility_Items_Feedback_Title',
                 'STR_A3A_Utility_Items_Insufficient_Funds',
                 'STR_A3A_Utility_Items_Last_Time_Purchase',
                 'STR_A3A_Utility_Items_Name_ammostation',
                 'STR_A3A_Utility_Items_Name_fueldrum',
                 'STR_A3A_Utility_Items_Name_fueltank',
                 'STR_A3A_Utility_Items_Name_light',
                 'STR_A3A_Utility_Items_Name_lootbox',
                 'STR_A3A_Utility_Items_Name_medicalbox',
                 'STR_A3A_Utility_Items_Name_medicaltent',
                 'STR_A3A_Utility_Items_Name_repairstation',
                 'STR_A3A_Utility_Items_Purchase_Title',
                 'STR_A3A_actions_restore_units',
                 'STR_A3A_base_vehicleBoxRestore_healed',
                 'STR_A3A_base_vehicleBoxRestore_noreported',
                 'STR_A3A_base_vehicleBoxRestore_rearmed',
                 'STR_A3A_base_vehicleBoxRestore_refueled',
                 'STR_A3A_base_vehicleBoxRestore_repaired',
                 'STR_A3A_base_vehicleBoxRestore_restoration_title',
                 'STR_A3A_base_vehicleBoxRestore_restored_additive',
                 'STR_A3A_base_vehicleBoxRestore_usedRecently',
                 'STR_A3A_customHint_dismiss',
                 'STR_A3A_customHint_dismiss_no_key',
                 'STR_A3A_feedback_serverinfo',
                 'STR_A3A_feedback_serverinfo_adminsetup',
                 'STR_A3A_feedback_serverinfo_adminwait',
                 'STR_A3A_feedback_serverinfo_autostartwait',
                 'STR_A3A_feedback_serverinfo_background',
                 'STR_A3A_feedback_serverinfo_completed',
                 'STR_A3A_feedback_serverinfo_mismatch',
                 'STR_A3A_feedback_serverinfo_starting',
                 'STR_A3A_feedback_serverinfo_waitserver',
                 'STR_A3A_garrison_adding_to_garrison',
                 'STR_A3A_garrison_adding_to_garrison_hc',
                 'STR_A3A_garrison_error_enemies_near',
                 'STR_A3A_garrison_error_no_hr',
                 'STR_A3A_garrison_error_no_money',
                 'STR_A3A_garrison_error_no_mortar',
                 'STR_A3A_garrison_error_still_updating',
                 'STR_A3A_garrison_exceed_limit',
                 'STR_A3A_garrison_fail_already_in_garrison',
                 'STR_A3A_garrison_fail_dead_units',
                 'STR_A3A_garrison_fail_no_specific_squads',
                 'STR_A3A_garrison_fail_no_specific_units',
                 'STR_A3A_garrison_fail_not_markerzone',
                 'STR_A3A_garrison_fail_not_teamplayer',
                 'STR_A3A_garrison_fail_wrong_type',
                 'STR_A3A_garrison_fail_zone_lost',
                 'STR_A3A_garrison_full_limit',
                 'STR_A3A_garrison_header',
                 'STR_A3A_garrison_reached_limit',
                 'STR_A3A_garrison_recruit_success',
                 'STR_A3A_garrison_select_zone',
                 'STR_A3A_garrisons_header',
                 'STR_A3A_missioncheck_nonmodmission',
                 'STR_A3A_missioncheck_nonmodmission_title',
                 'STR_A3A_missioncheck_oldmission',
                 'STR_A3A_missioncheck_oldmission_title',
                 'STR_antistasi_credits_generic_missiondesc_text',
                 'STR_antistasi_credits_generic_missionname_text',
                 'STR_antistasi_credits_generic_overview_text',
                 'STR_antistasi_dialogs_AI_management',
                 'STR_antistasi_dialogs_AI_management_AI_control',
                 'STR_antistasi_dialogs_AI_management_AI_control_tooltip',
                 'STR_antistasi_dialogs_AI_management_SITREP',
                 'STR_antistasi_dialogs_AI_management_SITREP_tooltip',
                 'STR_antistasi_dialogs_AI_management_auto_heal',
                 'STR_antistasi_dialogs_AI_management_auto_heal_tooltip',
                 'STR_antistasi_dialogs_AI_management_auto_rearm',
                 'STR_antistasi_dialogs_AI_management_auto_rearm_tooltip',
                 'STR_antistasi_dialogs_AI_management_dismiss_units',
                 'STR_antistasi_dialogs_AI_management_dismiss_units_tooltip',
                 'STR_antistasi_dialogs_AI_management_garrison',
                 'STR_antistasi_dialogs_AI_management_garrison_tooltip',
                 'STR_antistasi_dialogs_AI_management_mount',
                 'STR_antistasi_dialogs_AI_management_mount_tooltips',
                 'STR_antistasi_dialogs_AI_management_squad_add_vehicle',
                 'STR_antistasi_dialogs_AI_management_squad_add_vehicle_tooltip',
                 'STR_antistasi_dialogs_build_button_no_text',
                 'STR_antistasi_dialogs_build_disband_units_button_text',
                 'STR_antistasi_dialogs_build_disband_units_button_tooltip',
                 'STR_antistasi_dialogs_build_frame_text',
                 'STR_antistasi_dialogs_build_minefield_button_text',
                 'STR_antistasi_dialogs_build_minefield_button_tooltip',
                 'STR_antistasi_dialogs_build_outpost_button_text',
                 'STR_antistasi_dialogs_build_outpost_button_tooltip',
                 'STR_antistasi_dialogs_build_recruit_units_button_text',
                 'STR_antistasi_dialogs_build_recruit_units_button_tooltip',
                 'STR_antistasi_dialogs_carpet_bombing',
                 'STR_antistasi_dialogs_carpet_bombing_add',
                 'STR_antistasi_dialogs_carpet_bombing_add_tooltip',
                 'STR_antistasi_dialogs_carpet_bombing_cluster',
                 'STR_antistasi_dialogs_carpet_bombing_he',
                 'STR_antistasi_dialogs_carpet_bombing_he_tooltip',
                 'STR_antistasi_dialogs_carpet_bombing_napalm',
                 'STR_antistasi_dialogs_carpet_bombing_tooltip',
                 'STR_antistasi_dialogs_commander_comm',
                 'STR_antistasi_dialogs_commander_comm_air_support',
                 'STR_antistasi_dialogs_commander_comm_air_support_tooltip',
                 'STR_antistasi_dialogs_commander_comm_clean',
                 'STR_antistasi_dialogs_commander_comm_clean_tooltip',
                 'STR_antistasi_dialogs_commander_comm_faction_garage',
                 'STR_antistasi_dialogs_commander_comm_faction_garage_tooltip',
                 'STR_antistasi_dialogs_commander_comm_recruit',
                 'STR_antistasi_dialogs_commander_comm_recruit_tooltip',
                 'STR_antistasi_dialogs_commander_comm_resign',
                 'STR_antistasi_dialogs_commander_comm_resign_tooltip',
                 'STR_antistasi_dialogs_commander_comm_roadblock',
                 'STR_antistasi_dialogs_commander_comm_roadblock_delete',
                 'STR_antistasi_dialogs_commander_comm_roadblock_delete_tooltip',
                 'STR_antistasi_dialogs_commander_comm_roadblock_tooltip',
                 'STR_antistasi_dialogs_commander_comm_sell',
                 'STR_antistasi_dialogs_commander_comm_sell_tooltip',
                 'STR_antistasi_dialogs_construction_menu',
                 'STR_antistasi_dialogs_construction_menu_bunker_concrete',
                 'STR_antistasi_dialogs_construction_menu_bunker_options',
                 'STR_antistasi_dialogs_construction_menu_bunker_options_tooltip',
                 'STR_antistasi_dialogs_construction_menu_bunker_tooltip',
                 'STR_antistasi_dialogs_construction_menu_bunker_type',
                 'STR_antistasi_dialogs_construction_menu_medium_trench',
                 'STR_antistasi_dialogs_construction_menu_medium_trench_tooltip',
                 'STR_antistasi_dialogs_construction_menu_sandbag',
                 'STR_antistasi_dialogs_construction_menu_small_trench',
                 'STR_antistasi_dialogs_construction_menu_small_trench_tooltip',
                 'STR_antistasi_dialogs_construction_menu_vehicle_obstacles',
                 'STR_antistasi_dialogs_construction_menu_vehicle_obstacles_tooltip',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_civ_boat_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_civ_heli_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_civ_offroad_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_civ_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_civ_truck_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_a_offroad_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_offroad_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_quad_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_aa_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_aa_tooltip',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_at_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_at_tooltip',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_mg_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_mg_tooltip',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_mortar_text',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_s_mortar_tooltip',
                 'STR_antistasi_dialogs_dialog_vehicle_purchase_military_truck_text',
                 'STR_antistasi_dialogs_diff_menu',
                 'STR_antistasi_dialogs_diff_menu_easy',
                 'STR_antistasi_dialogs_diff_menu_hard',
                 'STR_antistasi_dialogs_diff_menu_normal',
                 'STR_antistasi_dialogs_dismiss_menu',
                 'STR_antistasi_dialogs_dismiss_menu_dismiss',
                 'STR_antistasi_dialogs_dismiss_menu_dismiss_tooltip',
                 'STR_antistasi_dialogs_dismiss_menu_garrison',
                 'STR_antistasi_dialogs_dismiss_menu_garrison_tooltip',
                 'STR_antistasi_dialogs_gameMode_menu',
                 'STR_antistasi_dialogs_gameMode_menu_Reb_vs_Gov',
                 'STR_antistasi_dialogs_gameMode_menu_Reb_vs_Gov_and_Inv',
                 'STR_antistasi_dialogs_gameMode_menu_Reb_vs_Gov_vs_Inv',
                 'STR_antistasi_dialogs_gameMode_menu_Reb_vs_Inv',
                 'STR_antistasi_dialogs_garage_check',
                 'STR_antistasi_dialogs_garage_faction',
                 'STR_antistasi_dialogs_garage_personal',
                 'STR_antistasi_dialogs_garage_sell',
                 'STR_antistasi_dialogs_garage_sell_add',
                 'STR_antistasi_dialogs_garage_sell_sell',
                 'STR_antistasi_dialogs_garrison_recruit_frame_text',
                 'STR_antistasi_dialogs_garrison_spawn_aamissile_text',
                 'STR_antistasi_dialogs_garrison_spawn_at_text',
                 'STR_antistasi_dialogs_garrison_spawn_atmissile_text',
                 'STR_antistasi_dialogs_garrison_spawn_autorifleman_text',
                 'STR_antistasi_dialogs_garrison_spawn_grenadier_text',
                 'STR_antistasi_dialogs_garrison_spawn_marksman_text',
                 'STR_antistasi_dialogs_garrison_spawn_medic_text',
                 'STR_antistasi_dialogs_garrison_spawn_mortar_text',
                 'STR_antistasi_dialogs_garrison_spawn_rifleman_text',
                 'STR_antistasi_dialogs_garrison_spawn_squad_lead_text',
                 'STR_antistasi_dialogs_generic_button_back_text',
                 'STR_antistasi_dialogs_generic_button_back_tooltip',
                 'STR_antistasi_dialogs_generic_button_no_text',
                 'STR_antistasi_dialogs_generic_button_no_tooltip',
                 'STR_antistasi_dialogs_generic_button_yes_text',
                 'STR_antistasi_dialogs_generic_button_yes_tooltip',
                 'STR_antistasi_dialogs_hq_button_close_text',
                 'STR_antistasi_dialogs_hq_button_garage_text',
                 'STR_antistasi_dialogs_hq_button_garage_tooltip',
                 'STR_antistasi_dialogs_hq_button_garrisons_text',
                 'STR_antistasi_dialogs_hq_button_garrisons_tooltip',
                 'STR_antistasi_dialogs_hq_button_members_list_text',
                 'STR_antistasi_dialogs_hq_button_members_list_tooltip',
                 'STR_antistasi_dialogs_hq_button_move_headquarters_text',
                 'STR_antistasi_dialogs_hq_button_move_headquarters_tooltip',
                 'STR_antistasi_dialogs_hq_button_rebuild_assets_text',
                 'STR_antistasi_dialogs_hq_button_rebuild_assets_tooltip',
                 'STR_antistasi_dialogs_hq_button_train_ai_text',
                 'STR_antistasi_dialogs_hq_button_train_ai_tooltip',
                 'STR_antistasi_dialogs_hq_button_withdraw_text',
                 'STR_antistasi_dialogs_hq_button_withdraw_tooltip',
                 'STR_antistasi_dialogs_hq_frame_text',
                 'STR_antistasi_dialogs_lps_frame_text',
                 'STR_antistasi_dialogs_maps_ai_limiter',
                 'STR_antistasi_dialogs_maps_ai_limiter_tooltip',
                 'STR_antistasi_dialogs_maps_civ_config',
                 'STR_antistasi_dialogs_maps_civ_config_minus',
                 'STR_antistasi_dialogs_maps_civ_config_plus',
                 'STR_antistasi_dialogs_maps_civ_limit',
                 'STR_antistasi_dialogs_maps_civ_limit_tooltip',
                 'STR_antistasi_dialogs_maps_fps_limiter_minus',
                 'STR_antistasi_dialogs_maps_fps_limiter_plus',
                 'STR_antistasi_dialogs_maps_game_options',
                 'STR_antistasi_dialogs_maps_music',
                 'STR_antistasi_dialogs_maps_music_tooltip',
                 'STR_antistasi_dialogs_maps_save',
                 'STR_antistasi_dialogs_maps_save_tooltip',
                 'STR_antistasi_dialogs_maps_spawn_config',
                 'STR_antistasi_dialogs_maps_spawn_config_minus',
                 'STR_antistasi_dialogs_maps_spawn_config_plus',
                 'STR_antistasi_dialogs_maps_spawn_distance',
                 'STR_antistasi_dialogs_maps_spawn_distance_tooltip',
                 'STR_antistasi_dialogs_mbt_type',
                 'STR_antistasi_dialogs_minefield_button_anti_personel_text',
                 'STR_antistasi_dialogs_minefield_button_anti_personel_tooltip',
                 'STR_antistasi_dialogs_minefield_button_anti_tank_text',
                 'STR_antistasi_dialogs_minefield_button_anti_tank_tooltip',
                 'STR_antistasi_dialogs_minefield_button_remove_text',
                 'STR_antistasi_dialogs_minefield_button_remove_tooltip',
                 'STR_antistasi_dialogs_minefield_frame_text',
                 'STR_antistasi_dialogs_mission_menu_assassination_missions',
                 'STR_antistasi_dialogs_mission_menu_available_missions',
                 'STR_antistasi_dialogs_mission_menu_conquest_missions',
                 'STR_antistasi_dialogs_mission_menu_convoy_ambush',
                 'STR_antistasi_dialogs_mission_menu_destroy_missions',
                 'STR_antistasi_dialogs_mission_menu_logistics_missions',
                 'STR_antistasi_dialogs_mission_menu_logistics_missions_tooltip',
                 'STR_antistasi_dialogs_mission_menu_rescue_missions',
                 'STR_antistasi_dialogs_mission_menu_support_missions',
                 'STR_antistasi_dialogs_mission_menu_support_missions_tooltip',
                 'STR_antistasi_dialogs_mortar_type',
                 'STR_antistasi_dialogs_mortar_type_he',
                 'STR_antistasi_dialogs_mortar_type_laser',
                 'STR_antistasi_dialogs_mortar_type_smoke',
                 'STR_antistasi_dialogs_player_money',
                 'STR_antistasi_dialogs_player_money_add_member',
                 'STR_antistasi_dialogs_player_money_add_member_tooltip',
                 'STR_antistasi_dialogs_player_money_donate_faction',
                 'STR_antistasi_dialogs_player_money_donate_faction_tooltip',
                 'STR_antistasi_dialogs_player_money_donate_player',
                 'STR_antistasi_dialogs_player_money_remove_member',
                 'STR_antistasi_dialogs_player_money_remove_member_tooltip',
                 'STR_antistasi_dialogs_radio_comm',
                 'STR_antistasi_dialogs_radio_comm_ai_management',
                 'STR_antistasi_dialogs_radio_comm_ai_management_tooltip',
                 'STR_antistasi_dialogs_radio_comm_commander',
                 'STR_antistasi_dialogs_radio_comm_commander_tooltip',
                 'STR_antistasi_dialogs_radio_comm_construct',
                 'STR_antistasi_dialogs_radio_comm_construct_tooltip',
                 'STR_antistasi_dialogs_radio_comm_fast_travel',
                 'STR_antistasi_dialogs_radio_comm_fast_travel_tooltip',
                 'STR_antistasi_dialogs_radio_comm_garage',
                 'STR_antistasi_dialogs_radio_comm_garage_tooltip',
                 'STR_antistasi_dialogs_radio_comm_player_money',
                 'STR_antistasi_dialogs_radio_comm_player_money_tooltip',
                 'STR_antistasi_dialogs_radio_comm_undercover',
                 'STR_antistasi_dialogs_radio_comm_undercover_tooltip',
                 'STR_antistasi_dialogs_radio_comm_unlock_vehicle',
                 'STR_antistasi_dialogs_radio_comm_unlock_vehicle_tooltip',
                 'STR_antistasi_dialogs_rounds_number',
                 'STR_antistasi_dialogs_squad_manager',
                 'STR_antistasi_dialogs_squad_manager_add_vehicle',
                 'STR_antistasi_dialogs_squad_manager_add_vehicle_tooltip',
                 'STR_antistasi_dialogs_squad_manager_mount',
                 'STR_antistasi_dialogs_squad_manager_mount_tooltip',
                 'STR_antistasi_dialogs_squad_manager_squad_sitrep',
                 'STR_antistasi_dialogs_squad_manager_squad_sitrep_tooltip',
                 'STR_antistasi_dialogs_squad_manager_static_autotarget',
                 'STR_antistasi_dialogs_squad_manager_static_autotarget_tooltip',
                 'STR_antistasi_dialogs_squad_options',
                 'STR_antistasi_dialogs_squad_options_engineer',
                 'STR_antistasi_dialogs_squad_options_mg',
                 'STR_antistasi_dialogs_squad_options_mortar',
                 'STR_antistasi_dialogs_squad_options_normal',
                 'STR_antistasi_dialogs_squad_recruit',
                 'STR_antistasi_dialogs_squad_recruit_aa_car',
                 'STR_antistasi_dialogs_squad_recruit_at',
                 'STR_antistasi_dialogs_squad_recruit_at_car',
                 'STR_antistasi_dialogs_squad_recruit_inf',
                 'STR_antistasi_dialogs_squad_recruit_inf_team',
                 'STR_antistasi_dialogs_squad_recruit_mg',
                 'STR_antistasi_dialogs_squad_recruit_mortar',
                 'STR_antistasi_dialogs_squad_recruit_sniper',
                 'STR_antistasi_dialogs_strike_type',
                 'STR_antistasi_dialogs_strike_type_barrage',
                 'STR_antistasi_dialogs_strike_type_single',
                 'STR_antistasi_dialogs_toggle_info_bar_body_off',
                 'STR_antistasi_dialogs_toggle_info_bar_body_on',
                 'STR_antistasi_dialogs_toggle_info_bar_title',
                 'STR_antistasi_dialogs_unit_recruit_aamissile_text',
                 'STR_antistasi_dialogs_unit_recruit_antitank_text',
                 'STR_antistasi_dialogs_unit_recruit_atmissile_text',
                 'STR_antistasi_dialogs_unit_recruit_engineer_text',
                 'STR_antistasi_dialogs_unit_recruit_explosive_text',
                 'STR_antistasi_dialogs_unit_recruit_frame_text',
                 'STR_antistasi_dialogs_unit_recruit_grenadier_text',
                 'STR_antistasi_dialogs_unit_recruit_marksman_text',
                 'STR_antistasi_dialogs_unit_recruit_medic_text',
                 'STR_antistasi_dialogs_unit_recruit_mg_text',
                 'STR_antistasi_dialogs_unit_recruit_militiaman_text',
                 'STR_antistasi_dialogs_vehicle_manager',
                 'STR_antistasi_dialogs_vehicle_manager_add_air_support',
                 'STR_antistasi_dialogs_vehicle_manager_add_air_support_tooltip',
                 'STR_antistasi_dialogs_vehicle_manager_garage_sell_vehicle',
                 'STR_antistasi_dialogs_vehicle_manager_garage_sell_vehicle_tooltip',
                 'STR_antistasi_dialogs_vehicle_manager_unlock_vehicle',
                 'STR_antistasi_dialogs_vehicle_manager_unlock_vehicle_tooltip',
                 'STR_antistasi_dialogs_vehicle_manager_veh_query',
                 'STR_antistasi_dialogs_vehicle_manager_vehicles_squads',
                 'STR_antistasi_dialogs_vehicle_manager_vehicles_squads_tooltip',
                 'STR_antistasi_dialogs_vehicle_purchase_buy_text',
                 'STR_antistasi_dialogs_vehicle_purchase_buy_tooltip',
                 'STR_antistasi_dialogs_vehicle_purchase_civie_text',
                 'STR_antistasi_dialogs_vehicle_purchase_civie_tooltip',
                 'STR_antistasi_dialogs_vehicle_purchase_military_text',
                 'STR_antistasi_dialogs_vehicle_purchase_military_tooltip',
                 'STR_antistasi_journal_entry_header_AI_1',
                 'STR_antistasi_journal_entry_header_AI_2',
                 'STR_antistasi_journal_entry_header_AI_3',
                 'STR_antistasi_journal_entry_header_AI_4',
                 'STR_antistasi_journal_entry_header_AI_5',
                 'STR_antistasi_journal_entry_header_AI_6',
                 'STR_antistasi_journal_entry_header_AI_7',
                 'STR_antistasi_journal_entry_header_Credits_1',
                 'STR_antistasi_journal_entry_header_Credits_2',
                 'STR_antistasi_journal_entry_header_Credits_3',
                 'STR_antistasi_journal_entry_header_Default_1',
                 'STR_antistasi_journal_entry_header_Default_2',
                 'STR_antistasi_journal_entry_header_Default_3',
                 'STR_antistasi_journal_entry_header_Diary_1',
                 'STR_antistasi_journal_entry_header_Diary_2',
                 'STR_antistasi_journal_entry_header_Diary_3',
                 'STR_antistasi_journal_entry_header_Diary_4',
                 'STR_antistasi_journal_entry_header_Diary_5',
                 'STR_antistasi_journal_entry_header_Diary_6',
                 'STR_antistasi_journal_entry_header_Features_1',
                 'STR_antistasi_journal_entry_header_Features_10',
                 'STR_antistasi_journal_entry_header_Features_11',
                 'STR_antistasi_journal_entry_header_Features_12',
                 'STR_antistasi_journal_entry_header_Features_13',
                 'STR_antistasi_journal_entry_header_Features_14',
                 'STR_antistasi_journal_entry_header_Features_15',
                 'STR_antistasi_journal_entry_header_Features_16',
                 'STR_antistasi_journal_entry_header_Features_17',
                 'STR_antistasi_journal_entry_header_Features_2',
                 'STR_antistasi_journal_entry_header_Features_3',
                 'STR_antistasi_journal_entry_header_Features_4',
                 'STR_antistasi_journal_entry_header_Features_5',
                 'STR_antistasi_journal_entry_header_Features_6',
                 'STR_antistasi_journal_entry_header_Features_7',
                 'STR_antistasi_journal_entry_header_Features_8',
                 'STR_antistasi_journal_entry_header_Features_9',
                 'STR_antistasi_journal_entry_header_Options_1',
                 'STR_antistasi_journal_entry_header_Options_2',
                 'STR_antistasi_journal_entry_header_Options_3',
                 'STR_antistasi_journal_entry_header_Options_4',
                 'STR_antistasi_journal_entry_header_Options_5',
                 'STR_antistasi_journal_entry_header_Options_6',
                 'STR_antistasi_journal_entry_header_Options_7',
                 'STR_antistasi_journal_entry_header_Options_8',
                 'STR_antistasi_journal_entry_header_SpecialK_1',
                 'STR_antistasi_journal_entry_header_SpecialK_2',
                 'STR_antistasi_journal_entry_header_SpecialK_3',
                 'STR_antistasi_journal_entry_header_SpecialK_4',
                 'STR_antistasi_journal_entry_header_SpecialK_5',
                 'STR_antistasi_journal_entry_header_SpecialK_6',
                 'STR_antistasi_journal_entry_header_commander_1',
                 'STR_antistasi_journal_entry_header_commander_10',
                 'STR_antistasi_journal_entry_header_commander_11',
                 'STR_antistasi_journal_entry_header_commander_12',
                 'STR_antistasi_journal_entry_header_commander_13',
                 'STR_antistasi_journal_entry_header_commander_14',
                 'STR_antistasi_journal_entry_header_commander_15',
                 'STR_antistasi_journal_entry_header_commander_2',
                 'STR_antistasi_journal_entry_header_commander_3',
                 'STR_antistasi_journal_entry_header_commander_4',
                 'STR_antistasi_journal_entry_header_commander_5',
                 'STR_antistasi_journal_entry_header_commander_6',
                 'STR_antistasi_journal_entry_header_commander_7',
                 'STR_antistasi_journal_entry_header_commander_8',
                 'STR_antistasi_journal_entry_header_commander_9',
                 'STR_antistasi_journal_entry_header_gamemode',
                 'STR_antistasi_journal_entry_header_tutorial_1',
                 'STR_antistasi_journal_entry_header_tutorial_2',
                 'STR_antistasi_journal_entry_header_tutorial_3',
                 'STR_antistasi_journal_entry_header_tutorial_4',
                 'STR_antistasi_journal_entry_header_tutorial_5',
                 'STR_antistasi_journal_entry_header_tutorial_6',
                 'STR_antistasi_journal_entry_header_tutorial_7',
                 'STR_antistasi_journal_entry_text_AI_1',
                 'STR_antistasi_journal_entry_text_AI_2',
                 'STR_antistasi_journal_entry_text_AI_3',
                 'STR_antistasi_journal_entry_text_AI_4',
                 'STR_antistasi_journal_entry_text_AI_5',
                 'STR_antistasi_journal_entry_text_AI_6',
                 'STR_antistasi_journal_entry_text_AI_7',
                 'STR_antistasi_journal_entry_text_Credits_1',
                 'STR_antistasi_journal_entry_text_Credits_2',
                 'STR_antistasi_journal_entry_text_Credits_3',
                 'STR_antistasi_journal_entry_text_Default_1',
                 'STR_antistasi_journal_entry_text_Default_2',
                 'STR_antistasi_journal_entry_text_Default_3',
                 'STR_antistasi_journal_entry_text_Diary_1',
                 'STR_antistasi_journal_entry_text_Diary_2',
                 'STR_antistasi_journal_entry_text_Diary_3',
                 'STR_antistasi_journal_entry_text_Diary_4',
                 'STR_antistasi_journal_entry_text_Diary_5',
                 'STR_antistasi_journal_entry_text_Diary_6',
                 'STR_antistasi_journal_entry_text_Features_1',
                 'STR_antistasi_journal_entry_text_Features_10',
                 'STR_antistasi_journal_entry_text_Features_11',
                 'STR_antistasi_journal_entry_text_Features_12',
                 'STR_antistasi_journal_entry_text_Features_13',
                 'STR_antistasi_journal_entry_text_Features_14',
                 'STR_antistasi_journal_entry_text_Features_15',
                 'STR_antistasi_journal_entry_text_Features_16',
                 'STR_antistasi_journal_entry_text_Features_17',
                 'STR_antistasi_journal_entry_text_Features_2',
                 'STR_antistasi_journal_entry_text_Features_3',
                 'STR_antistasi_journal_entry_text_Features_4',
                 'STR_antistasi_journal_entry_text_Features_5',
                 'STR_antistasi_journal_entry_text_Features_6',
                 'STR_antistasi_journal_entry_text_Features_7',
                 'STR_antistasi_journal_entry_text_Features_8',
                 'STR_antistasi_journal_entry_text_Features_9',
                 'STR_antistasi_journal_entry_text_Options_1',
                 'STR_antistasi_journal_entry_text_Options_2',
                 'STR_antistasi_journal_entry_text_Options_3',
                 'STR_antistasi_journal_entry_text_Options_4',
                 'STR_antistasi_journal_entry_text_Options_5',
                 'STR_antistasi_journal_entry_text_Options_6',
                 'STR_antistasi_journal_entry_text_Options_7',
                 'STR_antistasi_journal_entry_text_Options_8',
                 'STR_antistasi_journal_entry_text_SpecialK_1',
                 'STR_antistasi_journal_entry_text_SpecialK_2',
                 'STR_antistasi_journal_entry_text_SpecialK_3',
                 'STR_antistasi_journal_entry_text_SpecialK_4',
                 'STR_antistasi_journal_entry_text_SpecialK_5',
                 'STR_antistasi_journal_entry_text_SpecialK_6',
                 'STR_antistasi_journal_entry_text_commander_1',
                 'STR_antistasi_journal_entry_text_commander_10',
                 'STR_antistasi_journal_entry_text_commander_11',
                 'STR_antistasi_journal_entry_text_commander_12',
                 'STR_antistasi_journal_entry_text_commander_13',
                 'STR_antistasi_journal_entry_text_commander_14',
                 'STR_antistasi_journal_entry_text_commander_15',
                 'STR_antistasi_journal_entry_text_commander_2',
                 'STR_antistasi_journal_entry_text_commander_3',
                 'STR_antistasi_journal_entry_text_commander_4',
                 'STR_antistasi_journal_entry_text_commander_5',
                 'STR_antistasi_journal_entry_text_commander_6',
                 'STR_antistasi_journal_entry_text_commander_7',
                 'STR_antistasi_journal_entry_text_commander_8',
                 'STR_antistasi_journal_entry_text_commander_9',
                 'STR_antistasi_journal_entry_text_gamemode_1',
                 'STR_antistasi_journal_entry_text_gamemode_2',
                 'STR_antistasi_journal_entry_text_gamemode_3',
                 'STR_antistasi_journal_entry_text_gamemode_4',
                 'STR_antistasi_journal_entry_text_tutorial_1',
                 'STR_antistasi_journal_entry_text_tutorial_2',
                 'STR_antistasi_journal_entry_text_tutorial_3',
                 'STR_antistasi_journal_entry_text_tutorial_4',
                 'STR_antistasi_journal_entry_text_tutorial_5',
                 'STR_antistasi_journal_entry_text_tutorial_6',
                 'STR_antistasi_journal_entry_text_tutorial_7',
                 'STR_antistasi_timeSpan_days',
                 'STR_antistasi_timeSpan_days_abbr',
                 'STR_antistasi_timeSpan_hours',
                 'STR_antistasi_timeSpan_hours_abbr',
                 'STR_antistasi_timeSpan_microseconds',
                 'STR_antistasi_timeSpan_microseconds_abbr',
                 'STR_antistasi_timeSpan_milliseconds',
                 'STR_antistasi_timeSpan_milliseconds_abbr',
                 'STR_antistasi_timeSpan_minutes',
                 'STR_antistasi_timeSpan_minutes_abbr',
                 'STR_antistasi_timeSpan_nanoseconds',
                 'STR_antistasi_timeSpan_nanoseconds_abbr',
                 'STR_antistasi_timeSpan_now',
                 'STR_antistasi_timeSpan_seconds',
                 'STR_antistasi_timeSpan_seconds_abbr']

    example_keys = [ExampleKeyData("STR_antistasi_dialogs_unit_recruit_mg_text", ArmaLanguage.ORIGINAL, "Recruit Autorifleman"),
                    ExampleKeyData("STR_antistasi_dialogs_vehicle_manager_garage_sell_vehicle", ArmaLanguage.CHINESESIMP, "存储\出售载具")]

    yield StringtableObjExpectedResult(header='<?xml version="1.0" encoding="utf-8"?>',
                                       project_name="A3-Antistasi",
                                       package_name="A3-Antistasi Complex",
                                       name="Complex",
                                       amount_containers=38,
                                       container_names=set(container_names),
                                       amount_keys=492,
                                       key_names=set(key_names),
                                       example_keys=tuple(example_keys),
                                       amount_entries=4312)
